const G = ['tradicional', '80s', '90s', '2000s', 'actual'];

// Tuplas: palabra, significado, ejemplo, colección, lugar, icono, dificultad, generaciones, nota de fuente.
const groups = [
  ['patio-recreo', [
    ['trompo','Juguete que gira sobre una punta al lanzarlo con una cuerda.','En el recreo hicimos bailar el trompo sobre el cemento.','juegos-ninez','todo-mexico','🪀',1,G],
    ['balero','Juguete de copa y pieza unidas por un cordón.','Mi abuelo me enseñó a ensartar el balero con paciencia.','juegos-ninez','todo-mexico','🪀',1,G],
    ['canicas','Bolitas de vidrio usadas en juegos de puntería.','Trazamos un círculo de tierra para jugar canicas.','juegos-ninez','todo-mexico','🔵',1,G],
    ['resortera','Horqueta con bandas elásticas usada para lanzar objetos.','Guardamos la resortera y nunca apuntamos a los animales.','juegos-ninez','todo-mexico','🌿',1,G],
    ['bote pateado','Juego de escondite en el que se libera al grupo pateando un bote.','En la calle jugamos bote pateado hasta que cayó la tarde.','juegos-ninez','todo-mexico','🥫',1,G],
    ['avioncito','Nombre mexicano de un juego de casillas que se recorre saltando.','Las niñas pintaron un avioncito de diez casillas en la banqueta.','juegos-ninez','todo-mexico','✈️',1,G],
    ['matatena','Juego de recoger piezas pequeñas mientras una pelota rebota.','En la mesa practicamos matatena durante la tarde.','juegos-ninez','todo-mexico','⭐',2,['tradicional','80s','90s','2000s']],
    ['resorte','Juego de saltos con una banda elástica sostenida entre dos personas.','En el recreo cantábamos secuencias mientras saltábamos el resorte.','juegos-ninez','todo-mexico','➰',1,G],
    ['lotería','Juego de cartas ilustradas que se anuncian en voz alta.','La familia llenó la mesa para jugar lotería el domingo.','juegos-ninez','todo-mexico','🃏',1,G],
    ['ronda infantil','Juego colectivo de canto y movimiento dispuesto en círculo.','En la primaria hicimos una ronda infantil al ritmo de una canción.','juegos-ninez','todo-mexico','⭕',1,G],
    ['encantados','Juego de persecución en el que tocar a alguien lo deja inmóvil.','En encantados, Luisa liberó a su equipo con un toque.','juegos-ninez','todo-mexico','🧊',1,G],
    ['cebollitas','Juego colectivo de fuerza en el que una fila intenta mantenerse unida.','Las cebollitas terminaron entre risas en el patio.','juegos-ninez','todo-mexico','🧅',2,['tradicional','80s','90s','2000s']],
    ['recreo','Descanso entre clases para comer, conversar o jugar.','Durante el recreo compartimos fruta y jugamos futbol.','escuela-mexicana','todo-mexico','🔔',1,G],
    ['cooperativa escolar','Puesto organizado dentro de una escuela para vender alimentos o útiles.','En la cooperativa escolar compramos fruta durante el recreo.','escuela-mexicana','todo-mexico','🏫',1,G],
    ['gis','Barra de yeso usada para escribir en el pizarrón.','La maestra escribió la fecha con un gis blanco.','escuela-mexicana','todo-mexico','🖍️',1,G],
    ['pizarrón','Superficie donde se escribe durante una clase.','Copiamos del pizarrón una estrofa del poema.','escuela-mexicana','todo-mexico','🧑‍🏫',1,G],
    ['basta','Juego de lápiz y papel para escribir palabras por categorías y letra.','En la hora libre jugamos basta con nombres, lugares y frutas.','juegos-ninez','todo-mexico','📝',1,G],
    ['estampita','Imagen pequeña que se intercambia o colecciona.','Cambiamos una estampita repetida al salir de clases.','juegos-ninez','todo-mexico','🖼️',1,['80s','90s','2000s','actual']],
    ['reata','Cuerda resistente que también se usa para saltar.','Dos amigas giraron la reata mientras las demás saltaban.','juegos-ninez','todo-mexico','➰',2,G],
    ['papalote','Armazón ligera con papel que vuela sostenida por un hilo.','Elevamos el papalote cuando comenzó a soplar el viento.','juegos-ninez','todo-mexico','🪁',1,G],
  ]],
  ['casa-abuela', [
    ['molinillo','Utensilio de madera que espuma bebidas de chocolate.','La abuela giró el molinillo entre las palmas para servir chocolate.','cocina-bebidas','todo-mexico','🥄',1,G],
    ['comal','Plancha circular donde se cuecen o calientan alimentos.','Calentamos las tortillas directamente sobre el comal.','cocina-bebidas','todo-mexico','🫓',1,G],
    ['metate','Piedra rectangular usada para moler con otra pieza de piedra.','En la cocina antigua conservan un metate de piedra volcánica.','cocina-bebidas','todo-mexico','🪨',2,G],
    ['jarrito','Vasija pequeña de barro usada para servir bebidas.','Me sirvieron café de olla en un jarrito de barro.','cocina-bebidas','todo-mexico','🏺',1,G],
    ['teleteatro','Representación dramática producida especialmente para la televisión.','Mi abuela recordaba el teleteatro que reunía a la familia frente al aparato.','tele-cultura-popular','todo-mexico','📺',2,['tradicional','80s']],
    ['sobremesa','Conversación que continúa después de terminar la comida.','La sobremesa del domingo se alargó entre recuerdos familiares.','dichos-casa','todo-mexico','☕',1,G],
    ['apapacho','Muestra afectuosa de cariño o consuelo.','Cuando llegué triste, mi tía me recibió con un apapacho.','dichos-casa','todo-mexico','🤗',1,G],
    ['provecho','Expresión de cortesía dirigida a quien está comiendo.','Al pasar junto a la mesa dijimos provecho a la familia.','dichos-casa','todo-mexico','🍽️',1,G],
    ['mande','Respuesta cortés usada al atender un llamado.','Cuando su mamá la llamó desde la cocina, Elena respondió mande.','dichos-casa','todo-mexico','👂',1,G],
    ['aguas','Aviso coloquial para pedir cuidado o advertir un riesgo.','¡Aguas con el escalón!, avisó mi abuelo al entrar.','dichos-casa','todo-mexico','⚠️',1,G],
    ['ahorita','Expresión cuyo tiempo exacto depende del contexto.','Ahorita termino de barrer y te ayudo con la mesa.','dichos-casa','todo-mexico','⏱️',1,G],
    ['pilón','Cantidad adicional que se entrega como cortesía.','La marchanta puso dos mandarinas de pilón en la bolsa.','dichos-casa','todo-mexico','➕',2,G],
    ['chiquihuite','Canasta tejida de fibras vegetales para guardar o transportar cosas.','Las tortillas llegaron a la mesa dentro de un chiquihuite.','oficios-artesanias','todo-mexico','🧺',2,G],
    ['petate','Estera tejida con fibras de palma.','Extendieron el petate para descansar bajo la sombra.','oficios-artesanias','todo-mexico','🧶',2,G],
    ['radionovela','Relato dramático por episodios producido para escucharse en la radio.','La familia seguía la radionovela cada tarde y comentaba el episodio.','tele-cultura-popular','todo-mexico','📻',2,['tradicional','80s','90s']],
    ['atole','Bebida caliente y espesa preparada principalmente con maíz.','En una mañana fría desayunamos atole de vainilla.','cocina-bebidas','todo-mexico','🥣',1,G],
    ['champurrado','Bebida de masa de maíz preparada con chocolate.','Acompañamos los tamales con una taza de champurrado.','cocina-bebidas','todo-mexico','☕',1,G],
    ['pan dulce','Conjunto de piezas de panadería de formas y sabores variados.','Elegimos conchas y cuernitos de la charola de pan dulce.','dulces-antojitos','todo-mexico','🥐',1,G],
    ['cajeta','Dulce espeso elaborado tradicionalmente con leche de cabra.','Untamos un poco de cajeta sobre el pan tostado.','dulces-antojitos','todo-mexico','🍯',1,G],
    ['historieta mexicana','Relato ilustrado por viñetas producido dentro de la tradición editorial nacional.','En casa conservaban una historieta mexicana junto a periódicos antiguos.','tele-cultura-popular','todo-mexico','🗯️',2,['tradicional','80s','90s','2000s','actual']],
  ]],
  ['calle-barrio', [
    ['banqueta','Franja elevada destinada al paso de peatones junto a una calle.','Nos sentamos en la banqueta a platicar al caer la tarde.','vida-barrio','todo-mexico','🚶',1,G],
    ['tiendita','Comercio pequeño de barrio con productos cotidianos.','Fui a la tiendita por huevos y jabón para la casa.','vida-barrio','todo-mexico','🏪',1,G],
    ['vecindad','Vivienda colectiva organizada alrededor de patios compartidos.','La vecindad celebró la posada en el patio central.','vida-barrio','cdmx','🏘️',2,G],
    ['sonidero','Persona o colectivo que anima bailes populares con equipo de sonido.','El sonidero mandó saludos a las familias del barrio.','musica-mexicana','cdmx','🔊',2,['80s','90s','2000s','actual']],
    ['cascarita','Partido informal y generalmente breve de futbol.','Armamos una cascarita con dos mochilas como porterías.','vida-barrio','todo-mexico','⚽',1,G],
    ['talacha','Trabajo manual de reparación o mantenimiento, a menudo ocasional.','El sábado hicimos la talacha de pintar la reja.','vida-barrio','todo-mexico','🔧',2,G],
    ['chamba','Trabajo u ocupación, en registro coloquial.','Consiguió una chamba cerca de su colonia.','vida-barrio','todo-mexico','🧰',1,G],
    ['cuate','Amigo o compañero cercano, en registro coloquial.','Me encontré a un cuate de la secundaria en el parque.','vida-barrio','todo-mexico','🤝',1,G],
    ['Cine de Oro','Periodo de gran desarrollo y proyección del cine mexicano entre las décadas de 1930 y 1950.','El cineclub del barrio proyectó una película restaurada del Cine de Oro.','tele-cultura-popular','todo-mexico','🎞️',2,G],
    ['alburear','Participar en un intercambio de albur mediante ingenio verbal y acuerdo entre quienes juegan.','En el taller practicaron cómo alburear con ingenio, acuerdo y sin insultos.','albures-picaresca','todo-mexico','😉',2,G],
    ['echar la mano','Ayudar a alguien con una tarea o dificultad.','Los vecinos nos echaron la mano para mover las mesas.','dichos-casa','todo-mexico','🫱',1,G],
    ['hacer la vaquita','Reunir pequeñas aportaciones de varias personas para un gasto común.','Hicimos la vaquita para comprar pintura para la cancha.','vida-barrio','todo-mexico','🐄',2,G],
    ['carpa','Espectáculo popular itinerante de teatro, música y comicidad bajo una lona.','La exposición recordó la carpa como semillero de artistas populares mexicanos.','tele-cultura-popular','cdmx','🎪',2,['tradicional','80s']],
    ['pesero','Nombre coloquial de ciertos vehículos de transporte público capitalino.','El pesero avanzó por la avenida durante la hora pico.','regiones-hablas','cdmx','🚐',2,['80s','90s','2000s','actual']],
    ['regio','Forma coloquial de referirse a alguien o algo de Monterrey.','Mi amigo regio nos explicó una tradición de su ciudad.','regiones-hablas','monterrey','🏔️',2,G],
    ['tapatío','Gentilicio de quien es originario de Guadalajara.','Una artesana tapatía presentó su trabajo en la plaza.','regiones-hablas','guadalajara','🏛️',2,G],
    ['chilango','Gentilicio coloquial asociado con la Ciudad de México.','El cronista chilango narró cómo cambió su colonia.','regiones-hablas','cdmx','🚇',2,G],
    ['doble sentido','Expresión que admite una interpretación adicional, a menudo humorística.','El comediante usó un doble sentido blanco que entendió toda la familia.','albures-picaresca','todo-mexico','💬',2,G],
    ['albur','Juego verbal mexicano basado en dobles sentidos y respuestas ingeniosas.','El taller explicó el albur como tradición oral que exige consentimiento.','albures-picaresca','todo-mexico','😉',3,['tradicional','80s','90s','2000s','actual']],
    ['picardía verbal','Humor ingenioso que juega con las palabras sin necesidad de ser explícito.','La conversación tuvo picardía verbal, pero siempre respetó a quienes participaban.','albures-picaresca','todo-mexico','😏',3,G],
    ['cibercafé','Local que ofrece computadoras y conexión a internet por tiempo.','En los dos mil íbamos al cibercafé del barrio para imprimir la tarea.','mexico-digital','todo-mexico','🖥️',2,['90s','2000s','actual']],
    ['poner saldo','Comprar crédito para usar una línea móvil de prepago.','Pasé a la tiendita a poner saldo antes de llamar a mi mamá.','mexico-digital','todo-mexico','📱',2,['2000s','actual']],
    ['cadena de buenos días','Mensaje digital de saludo que se reenvía entre familiares, amistades o vecinos.','La cadena de buenos días llegó al grupo vecinal con flores y una taza de café.','mexico-digital','todo-mexico','🌹',2,['2000s','actual']],
    ['sticker de buenos días','Imagen de saludo matutino que circula en conversaciones digitales.','El grupo familiar recibió un sticker de buenos días antes de organizar la comida.','mexico-digital','todo-mexico','🌞',2,['2000s','actual']],
    ['grupo de la familia','Conversación digital de parientes usada para saludarse y organizar reuniones.','En el grupo de la familia acordamos quién llevaría tortillas y quién el guisado.','mexico-digital','todo-mexico','👨‍👩‍👧‍👦',2,['2000s','actual']],
  ]],
  ['mercado-antojitos', [
    ['tianguis','Mercado que se instala periódicamente en calles o espacios abiertos.','Los martes compramos fruta fresca en el tianguis del barrio.','vida-barrio','todo-mexico','🛍️',1,G],
    ['marchanta','Tratamiento coloquial para una vendedora o clienta de mercado.','La marchanta recomendó los tomates más maduros del puesto.','vida-barrio','todo-mexico','👩‍🌾',2,G],
    ['torta','Pan abierto y relleno con diversos ingredientes salados.','Pedimos una torta de frijoles con queso para el camino.','dulces-antojitos','todo-mexico','🥪',1,G],
    ['tamal','Masa de maíz rellena y cocida envuelta en hojas.','Compartimos un tamal de salsa verde durante el desayuno.','dulces-antojitos','todo-mexico','🫔',1,G],
    ['elote','Mazorca tierna de maíz, cocida o asada para comer.','En la plaza compramos un elote con limón y chile.','dulces-antojitos','todo-mexico','🌽',1,G],
    ['esquite','Granos de maíz preparados y servidos en vaso o recipiente.','La señora sirvió el esquite caliente con epazote.','dulces-antojitos','todo-mexico','🥣',1,G],
    ['garnacha','Nombre general de varios antojitos hechos con masa y acompañamientos.','En la feria probamos una garnacha recién salida del comal.','dulces-antojitos','todo-mexico','🌮',2,G],
    ['quesadilla','Tortilla doblada con queso u otros guisos, según la región.','Pedimos una quesadilla y aclaramos el relleno al ordenar.','dulces-antojitos','todo-mexico','🌮',1,G],
    ['tlacoyo','Pieza ovalada de masa rellena, cocida en comal.','El tlacoyo de haba llegó con nopales y salsa.','dulces-antojitos','cdmx','🫓',2,G],
    ['memela','Tortilla gruesa de masa con asiento y diversos acompañamientos.','En Oaxaca desayunamos una memela caliente en el mercado.','dulces-antojitos','oaxaca','🫓',2,G],
    ['cemita','Pan poblano y preparación rellena hecha con ese pan.','La cemita poblana llevaba quesillo, aguacate y pápalo.','dulces-antojitos','puebla','🥪',2,G],
    ['tlayuda','Tortilla oaxaqueña grande y firme que se sirve con diversos ingredientes.','Compartimos una tlayuda con frijoles y quesillo en Oaxaca.','dulces-antojitos','oaxaca','🫓',2,G],
    ['cochinita pibil','Carne adobada cocida tradicionalmente con técnica de horno de tierra.','En Yucatán sirvieron cochinita pibil con cebolla morada.','cocina-bebidas','yucatan','🍖',2,G],
    ['pozol','Bebida de maíz, común en el sureste mexicano y con variantes regionales.','En Tabasco tomamos pozol frío durante una tarde calurosa.','cocina-bebidas','tabasco','🥤',2,G],
    ['tejate','Bebida oaxaqueña de maíz y cacao con ingredientes aromáticos.','La vendedora batió el tejate antes de servirlo en una jícara.','cocina-bebidas','oaxaca','🥣',2,G],
    ['agua fresca','Bebida de agua preparada con fruta, semillas o flores.','Llenamos una jarra de agua fresca de jamaica para la comida.','cocina-bebidas','todo-mexico','🥤',1,G],
    ['chile en nogada','Platillo poblano de chile relleno cubierto con salsa de nuez.','En temporada compartimos un chile en nogada en Puebla.','cocina-bebidas','puebla','🌶️',2,G],
    ['corunda','Tamal michoacano de forma característica, envuelto en hojas de maíz.','La corunda llegó acompañada con crema y salsa.','dulces-antojitos','michoacan','🫔',2,G],
    ['marquesita','Postre yucateco crujiente, enrollado con distintos rellenos.','En Mérida pedimos una marquesita de queso con cajeta.','dulces-antojitos','yucatan','🧇',2,['90s','2000s','actual']],
    ['palanqueta','Dulce hecho con semillas o nueces unidas por caramelo.','Llevamos una palanqueta de cacahuate para el viaje.','dulces-antojitos','todo-mexico','🥜',1,G],
  ]],
  ['feria-verbena', [
    ['papel picado','Adorno de papel recortado con diseños, usado en celebraciones.','Colgamos papel picado de colores sobre el patio de la fiesta.','fiestas-tradiciones','todo-mexico','🎊',1,G],
    ['posada','Celebración decembrina que recrea la petición de alojamiento.','La posada del barrio tuvo letanías, ponche y piñata.','fiestas-tradiciones','todo-mexico','🕯️',1,G],
    ['piñata','Recipiente decorado que se rompe para repartir fruta o dulces.','Las niñas esperaron su turno para pegarle a la piñata.','fiestas-tradiciones','todo-mexico','🪅',1,G],
    ['verbena','Fiesta popular al aire libre con música, comida y puestos.','La verbena llenó la plaza de música y antojitos.','fiestas-tradiciones','todo-mexico','🎡',2,G],
    ['kermés','Fiesta comunitaria con juegos y venta de comida para reunir fondos.','La escuela organizó una kermés con tómbola y antojitos.','fiestas-tradiciones','todo-mexico','🎟️',1,G],
    ['tómbola','Sorteo de feria en el que se extraen números o boletos.','Ganamos una planta pequeña en la tómbola de la kermés.','fiestas-tradiciones','todo-mexico','🎫',2,G],
    ['castillo','Estructura de fuegos artificiales montada para fiestas populares.','El castillo iluminó la plaza bajo supervisión de los pirotécnicos.','fiestas-tradiciones','todo-mexico','🎆',2,G],
    ['torito','Armazón festiva con pirotecnia que una persona carga y hace bailar.','El torito recorrió la plaza manteniendo una zona de seguridad.','fiestas-tradiciones','todo-mexico','🐂',2,G],
    ['calenda','Desfile festivo oaxaqueño con música, figuras y participación comunitaria.','La calenda avanzó por Oaxaca entre bandas y marmotas.','fiestas-tradiciones','oaxaca','🥁',2,G],
    ['guelaguetza','Principio zapoteco de ayuda recíproca y nombre de una celebración oaxaqueña.','La explicación presentó la Guelaguetza como reciprocidad y encuentro cultural.','fiestas-tradiciones','oaxaca','🌺',3,G,'Del zapoteco; se asocia con reciprocidad y ofrenda.'],
    ['noche de rábanos','Exhibición oaxaqueña de figuras talladas en rábanos cada diciembre.','Visitamos la Noche de Rábanos y observamos escenas talladas.','fiestas-tradiciones','oaxaca','🥬',3,G],
    ['parachico','Danzante tradicional de la Fiesta Grande de Chiapa de Corzo.','El parachico recorrió las calles con su montera y chinchín.','fiestas-tradiciones','chiapas','🎭',3,G],
    ['volador','Participante del rito de los Voladores, practicado por comunidades mesoamericanas.','El volador siguió el ritual guiado por portadores de la tradición.','fiestas-tradiciones','veracruz','🪶',3,G],
    ['ramada','Estructura festiva hecha con ramas; el uso cambia según la región.','La comunidad adornó la ramada para recibir a las familias.','fiestas-tradiciones','nayarit','🌿',2,G],
    ['paseo del pendón','Desfile tradicional asociado con celebraciones comunitarias de Guerrero.','Las delegaciones participaron en el Paseo del Pendón con sus danzas.','fiestas-tradiciones','guerrero','🚩',3,G],
    ['hanal pixán','Conmemoración maya yucateca dedicada a las ánimas.','La familia preparó el altar de Hanal Pixán con respeto y memoria.','fiestas-tradiciones','yucatan','🕯️',3,G,'Expresión maya yucateca traducida comúnmente como comida de las ánimas.'],
    ['janitzio','Isla michoacana conocida por su vida comunitaria y celebraciones de ánimas.','En Janitzio los visitantes respetaron las indicaciones de la comunidad.','lugares-mexico','michoacan','🏝️',2,G],
    ['comparsa','Grupo que participa con música, baile o disfraces en una fiesta.','La comparsa ensayó varias semanas antes del carnaval.','fiestas-tradiciones','todo-mexico','🎭',2,G],
    ['carnaval','Celebración pública previa a la Cuaresma, con variantes regionales.','El carnaval de Campeche reunió comparsas en el malecón.','fiestas-tradiciones','campeche','🎉',2,G],
    ['ofrenda','Conjunto de objetos y alimentos dedicado a recordar a quienes murieron.','La familia colocó fotografías y flores en la ofrenda.','fiestas-tradiciones','todo-mexico','🕯️',1,G],
    ['lucha libre','Espectáculo deportivo de combate con llaves, vuelos y personajes enmascarados.','La familia asistió a una función de lucha libre en la Arena México.','ciencia-inventos-deporte','cdmx','🤼',2,G],
  ]],
  ['musica-une', [
    ['mariachi','Conjunto musical y tradición interpretativa vinculada especialmente con Jalisco.','El mariachi abrió la serenata con sones y violines.','musica-mexicana','jalisco','🎺',1,G],
    ['jarana','Instrumento de cuerdas usado en diversas tradiciones musicales mexicanas.','La jarana marcó el ritmo durante el fandango.','musica-mexicana','veracruz','🪕',2,G],
    ['marimba','Instrumento de láminas de madera percutidas, arraigado en el sureste.','La marimba animó la plaza de Chiapas al atardecer.','musica-mexicana','chiapas','🎶',2,G],
    ['huapango','Familia de expresiones musicales y dancísticas con variantes regionales.','Las parejas zapatearon huapango sobre la tarima.','musica-mexicana','huasteca','🎻',2,G],
    ['son jarocho','Tradición musical y dancística de Veracruz y zonas vecinas.','En el fandango tocaron son jarocho con jarana y arpa.','musica-mexicana','veracruz','🎻',2,G],
    ['son huasteco','Género musical de la Huasteca interpretado comúnmente por un trío.','El trío cantó son huasteco con violín y dos guitarras.','musica-mexicana','huasteca','🎻',3,G],
    ['norteño','Género musical del norte de México asociado con acordeón y bajo sexto.','El conjunto norteño tocó una polka frente a la plaza.','musica-mexicana','nuevo-leon','🪗',2,G],
    ['orquesta típica','Conjunto que interpreta repertorio mexicano con cuerdas, salterios y otros instrumentos.','La orquesta típica interpretó arreglos de música tradicional mexicana.','musica-mexicana','todo-mexico','🎻',2,G,'Formato de concierto cultivado en México desde el siglo XIX.'],
    ['bolero','Género de canción romántica cultivado ampliamente en México.','El trío interpretó un bolero con voces y guitarras.','musica-mexicana','todo-mexico','🎙️',2,G],
    ['ranchera','Género de canción mexicana ligado al acompañamiento de mariachi.','La cantante interpretó una ranchera durante la serenata.','musica-mexicana','todo-mexico','🎤',2,G],
    ['corrido','Forma narrativa cantada que relata personas o acontecimientos.','El archivo sonoro conserva un corrido sobre la vida ferroviaria.','musica-mexicana','todo-mexico','📜',2,G],
    ['danzón','Género musical y baile de origen cubano con fuerte arraigo en México.','Varias parejas bailaron danzón en la plaza de Veracruz.','musica-mexicana','veracruz','💃',2,G],
    ['fandango','Fiesta comunitaria de música, baile y convivencia en varias regiones.','El fandango reunió a músicos y bailadoras alrededor de la tarima.','musica-mexicana','veracruz','🪵',2,G],
    ['zapateado','Percusión rítmica realizada con los pies durante ciertos bailes.','El zapateado resonó con claridad sobre la tarima de madera.','musica-mexicana','todo-mexico','👞',2,G],
    ['requinto','Guitarra pequeña de registro agudo usada en distintos conjuntos.','El requinto respondió a las voces con una breve melodía.','musica-mexicana','todo-mexico','🎸',2,G],
    ['bajo sexto','Instrumento de cuerdas característico de conjuntos norteños.','El bajo sexto sostuvo la armonía junto al acordeón.','musica-mexicana','nuevo-leon','🎸',3,G],
    ['vihuela','Instrumento pequeño de cuerdas que aporta ritmo al mariachi.','La vihuela acompañó a las trompetas con rasgueos firmes.','musica-mexicana','jalisco','🎸',3,G],
    ['guitarrón','Instrumento grave de gran caja usado en el mariachi.','El guitarrón marcó la base rítmica de la canción.','musica-mexicana','jalisco','🎸',3,G],
    ['tambora','Tambor grande presente en bandas y otras tradiciones regionales.','La tambora dio entrada a los metales durante el desfile.','musica-mexicana','todo-mexico','🥁',2,G],
    ['son calentano','Tradición musical de la región de Tierra Caliente compartida por Guerrero y estados vecinos.','Un conjunto de Guerrero interpretó son calentano con violín y guitarras.','musica-mexicana','guerrero','🎻',3,G,'La tradición abarca Tierra Caliente en Guerrero, Michoacán y el Estado de México; esta entrada representa su vertiente guerrerense.'],
  ]],
  ['mexico-regional', [
    ['ajijic','Población jalisciense situada a orillas del lago de Chapala.','En Ajijic caminamos por el malecón junto al lago.','lugares-mexico','jalisco','🌊',2,G],
    ['xochimilco','Zona lacustre y alcaldía del sur de la Ciudad de México.','En Xochimilco conocimos las chinampas con un guía local.','lugares-mexico','cdmx','🛶',2,G,'Topónimo de origen náhuatl.'],
    ['monte albán','Antigua ciudad zapoteca ubicada en los Valles Centrales de Oaxaca.','Desde Monte Albán observamos la amplitud del valle.','lugares-mexico','oaxaca','🏛️',3,G],
    ['cholula','Ciudad poblana de larga historia, conocida por su gran basamento piramidal.','En Cholula recorrimos la zona arqueológica y el museo.','lugares-mexico','puebla','⛪',2,G],
    ['pátzcuaro','Ciudad michoacana vinculada históricamente con la región del lago.','En Pátzcuaro visitamos talleres y caminamos por sus plazas.','lugares-mexico','michoacan','🏘️',2,G],
    ['taxco','Ciudad de Guerrero reconocida por su tradición platera.','En Taxco una artesana explicó el trabajo de la plata.','lugares-mexico','guerrero','⛰️',2,G],
    ['san cristóbal','Ciudad de los Altos de Chiapas con amplia diversidad cultural.','En San Cristóbal escuchamos varias lenguas en el mercado.','lugares-mexico','chiapas','🏘️',2,G],
    ['izamal','Ciudad yucateca con patrimonio maya y arquitectura virreinal.','Recorrimos Izamal con una guía nacida en la comunidad.','lugares-mexico','yucatan','🟨',2,G],
    ['edzná','Antigua ciudad maya situada en el actual estado de Campeche.','En Edzná observamos el manejo histórico del agua.','lugares-mexico','campeche','🏛️',3,G,'Topónimo maya.'],
    ['tulum','Ciudad maya amurallada situada en la costa de Quintana Roo.','Visitamos Tulum temprano para recorrer el sitio con calma.','lugares-mexico','quintana-roo','🌊',2,G,'Topónimo maya.'],
    ['comalcalco','Ciudad tabasqueña y sitio arqueológico maya construido con ladrillo.','El museo de Comalcalco explicó su arquitectura de ladrillo.','lugares-mexico','tabasco','🧱',3,G,'Topónimo de origen náhuatl.'],
    ['tepic','Capital de Nayarit y centro de una región cultural diversa.','En Tepic visitamos el museo regional antes de ir a la sierra.','lugares-mexico','nayarit','🏙️',2,G],
    ['huasteca','Región cultural compartida por varios estados del oriente mexicano.','La Huasteca reúne tradiciones distintas a través de varios estados.','regiones-hablas','huasteca','🗺️',2,G],
    ['chilangoísmo','Palabra o giro asociado con el habla de la Ciudad de México.','El glosario marcó el término como chilangoísmo y explicó su contexto.','regiones-hablas','cdmx','🗣️',3,['90s','2000s','actual']],
    ['regiomontano','Gentilicio formal de las personas originarias de Monterrey.','El investigador regiomontano documentó la memoria industrial local.','regiones-hablas','monterrey','🏔️',2,G],
    ['jarocho','Gentilicio y denominación cultural vinculada con Veracruz.','El músico jarocho explicó la función comunitaria del fandango.','regiones-hablas','veracruz','🌊',2,G],
    ['poblano','Gentilicio de las personas originarias del estado o ciudad de Puebla.','Una cocinera poblana compartió la historia de su recetario familiar.','regiones-hablas','puebla','🏺',1,G],
    ['purépecha','Nombre de un pueblo originario y su lengua, principalmente de Michoacán.','La maestra purépecha presentó un libro bilingüe en la escuela.','pueblos-originarios-lenguas','michoacan','🦋',3,G,'Nombre del pueblo y de una lengua de la familia tarasca.'],
    ['maya yucateco','Lengua maya hablada principalmente en la península de Yucatán.','El museo ofreció cédulas en español y maya yucateco.','pueblos-originarios-lenguas','yucatan','🌿',3,G,'Lengua de la familia maya.'],
    ['náayeri','Nombre con el que el pueblo cora se refiere a sí mismo y a su lengua.','Una autora náayeri presentó su poesía en edición bilingüe.','pueblos-originarios-lenguas','nayarit','🗣️',3,G,'Autodenominación asociada con el pueblo y lengua cora.'],
  ]],
  ['oficios-artesanias', [
    ['talavera','Cerámica vidriada elaborada bajo una tradición artesanal de Puebla y Tlaxcala.','El taller poblano mostró cada etapa de una pieza de talavera.','oficios-artesanias','puebla','🏺',2,G],
    ['barro negro','Tradición alfarera oaxaqueña asociada especialmente con San Bartolo Coyotepec.','La artesana bruñó una pieza de barro negro antes de cocerla.','oficios-artesanias','oaxaca','🏺',2,G],
    ['alebrije','Figura fantástica tallada en madera o modelada en cartonería, según la tradición.','El museo distinguió el alebrije de cartonería del tallado oaxaqueño.','oficios-artesanias','todo-mexico','🐉',2,G],
    ['cartonería','Técnica que modela papel y engrudo para crear figuras.','El cartonero formó una máscara mediante varias capas de cartonería.','oficios-artesanias','todo-mexico','🎭',2,G],
    ['papel amate','Soporte elaborado con cortezas mediante una técnica de origen mesoamericano.','La exposición presentó papel amate producido por artesanos de la sierra.','oficios-artesanias','puebla','📜',3,G],
    ['rebozo','Prenda rectangular tejida que se usa de diversas maneras.','La tejedora explicó cómo anudó el fleco del rebozo.','oficios-artesanias','todo-mexico','🧣',2,G],
    ['sarape','Prenda rectangular de abrigo, tejida con diseños variados.','El artesano mostró el telar donde tejió el sarape.','oficios-artesanias','todo-mexico','🧶',2,G],
    ['huipil','Prenda tradicional de origen mesoamericano, con variantes comunitarias.','La ficha identificó la comunidad y técnica del huipil exhibido.','oficios-artesanias','todo-mexico','👚',2,G,'Del náhuatl huipilli; la prenda tiene variantes entre numerosos pueblos.'],
    ['quechquémitl','Prenda indígena para la parte superior del cuerpo, formada por lienzos unidos.','La curadora explicó el tejido del quechquémitl de la Huasteca.','oficios-artesanias','huasteca','🧣',3,G,'Del náhuatl quechquemitl.'],
    ['deshilado','Técnica textil que retira y reorganiza hilos para formar diseños.','La bordadora trabajó el deshilado con luz natural.','oficios-artesanias','todo-mexico','🪡',2,G],
    ['telar de cintura','Telar tensado entre un punto fijo y una banda sujeta al cuerpo de quien teje.','La tejedora ajustó la tensión del telar de cintura antes de continuar.','oficios-artesanias','oaxaca','🧶',3,G],
    ['maque','Técnica artesanal de recubrimiento y decoración presente en México desde época antigua.','La artesana michoacana pulió cuidadosamente el maque de la batea.','oficios-artesanias','michoacan','🎨',3,G],
    ['platería','Oficio de trabajar la plata para crear objetos utilitarios o decorativos.','El platero de Taxco soldó una pieza en su banco de trabajo.','oficios-artesanias','guerrero','🥈',2,G],
    ['hojalata','Lámina metálica usada para crear objetos decorativos y utilitarios.','El artesano recortó la hojalata para formar un espejo.','oficios-artesanias','todo-mexico','🔨',2,G],
    ['cestería','Oficio de entrelazar fibras para fabricar recipientes y otros objetos.','La familia enseñó cómo seleccionar palma para la cestería.','oficios-artesanias','todo-mexico','🧺',2,G],
    ['laudero','Artesano que construye y repara instrumentos de cuerda.','El laudero ajustó la jarana antes del concierto.','oficios-artesanias','veracruz','🎸',3,G],
    ['alfarero','Persona que fabrica objetos de barro cocido.','El alfarero centró el barro húmedo sobre el torno.','oficios-artesanias','todo-mexico','🏺',2,G],
    ['chinampa','Parcela agrícola construida en zonas lacustres de poca profundidad.','La productora cultivó flores y hortalizas en la chinampa.','naturaleza-mexico','cdmx','🌱',2,G,'Del náhuatl chināmitl.'],
    ['milpa','Sistema agrícola mesoamericano centrado en maíz y cultivos asociados.','En la milpa crecieron juntos maíz, frijol y calabaza.','naturaleza-mexico','todo-mexico','🌽',2,G,'Del náhuatl mīlpan.'],
    ['nixtamal','Maíz cocido con una sustancia alcalina para preparar masa y otros alimentos.','En el molino transformaron el nixtamal en masa fresca.','cocina-bebidas','todo-mexico','🌽',2,G,'Del náhuatl nextamalli.'],
  ]],
  ['historias-leyendas', [
    ['Llorona','Personaje de una leyenda difundida en México con numerosas versiones.','La narradora contó una versión local de la Llorona sin presentarla como única.','leyendas-relatos','todo-mexico','👻',2,G],
    ['nahual','Ser humano con capacidad de transformarse o vínculo ritual, según diversas tradiciones.','El relato describió al nahual según la memoria de esa comunidad.','leyendas-relatos','todo-mexico','🐆',3,G,'Del náhuatl nāhualli; los sentidos varían entre tradiciones.'],
    ['alux','Ser de relatos mayas de la península de Yucatán.','La abuela narró una historia de aluxes ubicada cerca de la milpa.','leyendas-relatos','yucatan','🌿',3,G,'Término de origen maya yucateco.'],
    ['chaneque','Ser asociado con montes y aguas en distintas tradiciones del centro y Golfo.','El cuento del chaneque advertía cuidar el bosque y sus manantiales.','leyendas-relatos','veracruz','🌳',3,G,'Del náhuatl; las características cambian según la región.'],
    ['tzitzimime','Seres celestes de la tradición nahua, descritos en fuentes históricas.','La mediadora mostró una imagen histórica de las tzitzimime en el códice.','leyendas-relatos','todo-mexico','✨',3,['tradicional'],'Término del náhuatl; plural castellanizado de tzitzimitl.'],
    ['Popocatépetl','Volcán activo del centro de México y figura de relatos ampliamente difundidos.','Desde Puebla observamos el Popocatépetl siguiendo los avisos oficiales.','naturaleza-mexico','puebla','🌋',2,G,'Topónimo de origen náhuatl.'],
    ['Iztaccíhuatl','Volcán del centro de México presente en relatos y memoria regional.','La silueta del Iztaccíhuatl apareció al despejarse el cielo.','naturaleza-mexico','puebla','🏔️',3,G,'Topónimo de origen náhuatl.'],
    ['Quetzalcóatl','Deidad mesoamericana relacionada con la serpiente emplumada en varias culturas.','El museo comparó representaciones de Quetzalcóatl de épocas distintas.','historia-personajes','todo-mexico','🐍',3,['tradicional'],'Nombre de origen náhuatl; sus atributos varían históricamente.'],
    ['Sor Juana','Escritora novohispana del siglo XVII, autora de poesía, teatro y prosa.','Leímos un poema de Sor Juana y comentamos su contexto novohispano.','historia-personajes','todo-mexico','📚',2,G],
    ['Morelos','José María Morelos, dirigente de la independencia de México.','El grupo revisó los Sentimientos de la Nación vinculados con Morelos.','historia-personajes','michoacan','📜',2,G],
    ['Benito Juárez','Presidente mexicano de origen zapoteco y figura central de la Reforma.','La clase situó a Benito Juárez en los conflictos políticos de su época.','historia-personajes','oaxaca','📜',2,G],
    ['Carmen Serdán','Revolucionaria poblana que participó en el movimiento antirreeleccionista.','El museo de Puebla recordó la participación política de Carmen Serdán.','historia-personajes','puebla','🕊️',2,G],
    ['Pakal','Gobernante maya de Palenque durante el periodo Clásico.','En Palenque estudiamos la inscripción asociada con el gobernante Pakal.','historia-personajes','chiapas','👑',3,G,'Nombre registrado en textos mayas; suele citarse como K’inich Janaab’ Pakal.'],
    ['códice','Libro manuscrito, especialmente los de tradición mesoamericana.','El facsímil del códice permitió observar signos y colores sin dañar el original.','historia-personajes','todo-mexico','📜',2,G],
    ['relato oral','Historia transmitida mediante la voz y recreada entre generaciones.','La investigadora pidió permiso antes de registrar el relato oral comunitario.','leyendas-relatos','todo-mexico','🗣️',2,G],
    ['Mulata de Córdoba','Personaje legendario veracruzano asociado con relatos coloniales de prodigio y persecución.','La narradora de Córdoba contó una versión local de la Mulata de Córdoba.','leyendas-relatos','veracruz','🕯️',3,G,'Leyenda con múltiples versiones; no debe leerse como biografía comprobada.'],
    ['Charro Negro','Jinete sobrenatural de relatos mexicanos que suele tentar o asustar a caminantes.','El abuelo contó que el Charro Negro aparecía en caminos solitarios.','leyendas-relatos','todo-mexico','🐎',3,G,'Motivo legendario difundido con variantes regionales.'],
    ['Planchada','Aparición de relatos hospitalarios mexicanos, descrita como una enfermera de uniforme impecable.','La enfermera aclaró que la Planchada pertenece a la tradición oral del hospital.','leyendas-relatos','todo-mexico','🏥',3,['80s','90s','2000s','actual'],'Leyenda urbana con versiones en distintos hospitales del país.'],
    ['Tisigua','Ser femenino de la tradición oral chiapaneca asociado con ríos y extravíos.','El relato chiapaneco advirtió que la Tisigua llamaba desde la orilla del río.','leyendas-relatos','chiapas','🌊',3,G,'La caracterización varía entre comunidades y narradores de Chiapas.'],
    ['Xtáabay','Personaje femenino sobrenatural de relatos mayas de la península de Yucatán.','La narradora yucateca situó a la Xtáabay junto a una ceiba del camino.','leyendas-relatos','yucatan','🌳',3,G,'Nombre de origen maya yucateco; existen diversas grafías y versiones.'],
  ]],
  ['mexico-profundo', [
    ['pelota mixteca','Juego de pelota practicado por comunidades de Oaxaca y su diáspora.','Dos equipos disputaron pelota mixteca con guantes elaborados para la modalidad.','ciencia-inventos-deporte','oaxaca','🥎',3,G,'Tradición deportiva viva con distintas modalidades.'],
    ['ulama','Juego de pelota de raíz mesoamericana que permanece vivo en el noroeste de México.','El documental mostró una partida de ulama guiada por sus jugadores tradicionales.','ciencia-inventos-deporte','todo-mexico','🏐',3,G,'Se practica especialmente en Sinaloa; se usa todo-mexico porque la taxonomía aún no incluye ese estado.'],
    ['juego de pelota mesoamericano','Conjunto de prácticas rituales y deportivas con variantes entre sociedades mesoamericanas.','El museo comparó canchas y reglas del juego de pelota mesoamericano en distintas épocas.','ciencia-inventos-deporte','todo-mexico','⚽',3,['tradicional'],'No existió una sola modalidad; las reglas y significados variaron por región y periodo.'],
    ['televisión a color','Campo tecnológico al que el ingeniero mexicano Guillermo González Camarena aportó sistemas propios.','El museo explicó con documentos el sistema de televisión a color de González Camarena.','ciencia-inventos-deporte','todo-mexico','📺',3,G,'González Camarena obtuvo en México la patente 40235 para su sistema tricromático secuencial de campos en 1940; no fue el único desarrollo mundial de televisión a color.'],
    ['náhuatl','Conjunto de variantes lingüísticas de la familia yuto-nahua habladas en México.','La biblioteca recibió libros escritos en varias formas de náhuatl.','pueblos-originarios-lenguas','todo-mexico','🗣️',3,G,'Lengua o agrupación de variantes de la familia yuto-nahua.'],
    ['mixteco','Conjunto de variantes lingüísticas de la familia otomangue.','El centro de salud preparó materiales en variantes de mixteco de la región.','pueblos-originarios-lenguas','oaxaca','🗣️',3,G,'Agrupación de variantes de la familia otomangue.'],
    ['zapoteco','Conjunto diverso de lenguas de la familia otomangue.','La radio comunitaria transmite noticias en una variante de zapoteco.','pueblos-originarios-lenguas','oaxaca','🗣️',3,G,'Agrupación lingüística de la familia otomangue.'],
    ['tsotsil','Lengua maya hablada principalmente en Chiapas.','La señal del museo incluyó una traducción al tsotsil local.','pueblos-originarios-lenguas','chiapas','🗣️',3,G,'Lengua de la familia maya.'],
    ['tseltal','Lengua maya hablada principalmente en Chiapas.','Varias familias escucharon el programa de radio en tseltal.','pueblos-originarios-lenguas','chiapas','🗣️',3,G,'Lengua de la familia maya.'],
    ['chontal de Tabasco','Nombre de una lengua maya hablada en Tabasco.','El archivo conserva grabaciones autorizadas en chontal de Tabasco.','pueblos-originarios-lenguas','tabasco','🗣️',3,G,'Lengua maya; sus hablantes también emplean la autodenominación yokot’an.'],
    ['yokot’an','Autodenominación relacionada con el pueblo y la lengua chontal de Tabasco.','La escritora presentó un poemario bilingüe en yokot’an y español.','pueblos-originarios-lenguas','tabasco','🗣️',3,G,'Autodenominación en la lengua conocida como chontal de Tabasco.'],
    ['wixárika','Autodenominación vinculada con el pueblo conocido también como huichol.','Un artista wixárika explicó la historia de su obra con sus propias palabras.','pueblos-originarios-lenguas','jalisco','🗣️',3,G,'Autodenominación del pueblo y su lengua.'],
    ['me’phaa','Autodenominación del pueblo y las lenguas conocidas también como tlapanecas.','La escuela produjo materiales con docentes hablantes de me’phaa.','pueblos-originarios-lenguas','guerrero','🗣️',3,G,'Autodenominación usada por comunidades de Guerrero.'],
    ['quelite','Nombre general de diversas plantas tiernas comestibles.','Recolectaron quelites conocidos localmente y los cocinaron con cuidado.','naturaleza-mexico','todo-mexico','🌿',2,G,'Del náhuatl quilitl.'],
    ['nopal','Planta del género Opuntia, de gran presencia alimentaria y cultural en México.','Cortamos nopales del huerto usando guantes y pinzas.','naturaleza-mexico','todo-mexico','🌵',1,G,'Del náhuatl nopalli.'],
    ['ajolote','Anfibio mexicano capaz de conservar rasgos larvarios en la adultez.','El proyecto restauró hábitat para el ajolote de Xochimilco.','naturaleza-mexico','cdmx','🦎',2,G,'Del náhuatl āxōlōtl.'],
    ['mariposa monarca','Mariposa migratoria que pasa el invierno en bosques del centro de México.','Observamos la mariposa monarca a distancia para no alterar el santuario.','naturaleza-mexico','michoacan','🦋',2,G],
    ['cero','Símbolo numérico desarrollado de forma independiente por civilizaciones, incluida la maya.','La sala explicó el uso maya del cero mediante inscripciones fechadas.','ciencia-inventos-deporte','todo-mexico','0️⃣',3,G],
    ['colorante grana','Pigmento rojo obtenido de la grana cochinilla criada sobre nopales.','El taller tiñó lana con colorante de grana siguiendo medidas precisas.','ciencia-inventos-deporte','oaxaca','🔴',3,G],
    ['chinanteco','Conjunto de lenguas otomangues habladas principalmente en el norte de Oaxaca.','La biblioteca comunitaria presentó materiales en la variante chinanteca local.','pueblos-originarios-lenguas','oaxaca','🗣️',3,G,'Agrupación de variantes de la familia otomangue; cada comunidad identifica su forma local.'],
  ]],
];

let order = 0;
const SPORTS = new Set(['pelota mixteca', 'lucha libre', 'ulama', 'juego de pelota mesoamericano']);
const normalizeConceptVariant = (word) => word.toLocaleLowerCase('es-MX').replace(/ñ/g, '\u0000')
  .normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/\u0000/g, 'ñ')
  .replace(/[^a-z0-9ñ]+/g, '-').replace(/^-|-$/g, '');
// Equivalencias conocidas que la revisión editorial considera un solo concepto.
// La revisión manual sigue siendo necesaria para descubrir nuevas familias.
const SEMANTIC_CONCEPT_OVERRIDES = {
  avion: 'juego-casillas-salto', avioncito: 'juego-casillas-salto', rayuela: 'juego-casillas-salto',
  laqueado: 'maque-artesanal', maque: 'maque-artesanal',
  escondidas: 'juego-escondidas', escondidillas: 'juego-escondidas',
  chiquihuite: 'chiquihuite', chiquiguite: 'chiquihuite',
};
const conceptKey = (word) => {
  const normalized = normalizeConceptVariant(word);
  return SEMANTIC_CONCEPT_OVERRIDES[normalized] || normalized;
};
const MEXICO_VIVIDO_WORDS = groups.flatMap(([pathId, entries]) => entries.map((entry) => {
  const [word, meaning, example, collectionId, placeId, icon, difficulty = 2, generation = G, sourceNote] = entry;
  order += 1;
  return {
    word, meaning, example, collectionId, pathId, placeId, difficulty, generation,
    rating: 'familiar', icon, order, conceptId: conceptKey(word),
    ...(SPORTS.has(word) ? { topic: 'deporte' } : {}),
    ...(sourceNote ? { sourceNote } : {}),
  };
}));

const REMOVED_WORDS = [
  { word: 'cadena de tías', reason: 'Formulación retirada para no asociar una práctica digital familiar con un género específico.' },
  { word: 'rayuela', reason: 'Duplicaba el concepto de avioncito; se conservó la variante mexicana del juego.' },
  { word: 'laqueado', reason: 'Duplicaba el concepto artesanal de maque; se sustituyó por telar de cintura.' },
  { word: 'costa', reason: 'Región demasiado genérica; se sustituyó por lugares canónicos concretos.' },
  { word: 'influencer', reason: 'Concepto efímero y no específicamente mexicano.' },
  { word: 'yucateco genérico', reason: 'Mezclaba culturas y estados distintos del sureste.' },
  { word: 'español', reason: 'Duplicado editorial sin anclaje en un camino cultural.' },
  { word: 'niño', reason: 'Término general sustituido por experiencias concretas de niñez mexicana.' },
];

const review = (category, reason) => ({ category, reason });
const FIRST_FIFTY_CONTEXT_REVIEW = {
  trompo: review('juego', 'Juego de destreza muy recordado en patios y recreos mexicanos.'),
  balero: review('juego', 'Juguete tradicional presente en hogares y ferias populares de México.'),
  canicas: review('juego', 'Juego de tierra y puntería arraigado en la memoria infantil mexicana.'),
  resortera: review('juego', 'Objeto habitual de la infancia rural y barrial mexicana, tratado con cuidado.'),
  'bote pateado': review('juego', 'Juego de calle documentado en recuerdos de infancia de distintas regiones mexicanas.'),
  avioncito: review('juego', 'Nombre mexicano muy extendido para el juego de casillas y saltos.'),
  matatena: review('juego', 'Juego de coordinación conocido por varias generaciones de niñas y niños mexicanos.'),
  resorte: review('juego', 'Juego cantado de recreo practicado en escuelas y banquetas mexicanas.'),
  lotería: review('juego', 'Juego ilustrado inseparable de reuniones familiares y ferias mexicanas.'),
  'ronda infantil': review('juego', 'Experiencia escolar compartida mediante cantos tradicionales en México.'),
  encantados: review('juego', 'Nombre ampliamente usado en México para este juego colectivo de persecución.'),
  cebollitas: review('juego', 'Juego colectivo reconocido en memorias de patios escolares mexicanos.'),
  recreo: review('escuela', 'Momento escolar asociado aquí con compartir fruta y jugar futbol en México.'),
  'cooperativa escolar': review('escuela', 'Puesto cotidiano de alimentos y útiles dentro de muchas escuelas mexicanas.'),
  basta: review('escuela', 'Juego de categorías con lápiz y papel frecuente en salones mexicanos.'),
  estampita: review('escuela', 'Objeto de intercambio coleccionable recordado a la salida de escuelas mexicanas.'),
  reata: review('lenguaje', 'Voz mexicana usada aquí para la cuerda de los juegos de salto.'),
  papalote: review('lenguaje', 'Palabra de origen náhuatl cotidiana en México para el juguete volador.'),
  molinillo: review('cocina', 'Utensilio de madera ligado al chocolate preparado en cocinas mexicanas.'),
  comal: review('cocina', 'Superficie central para tortillas y guisos en la cocina cotidiana mexicana.'),
  metate: review('cocina', 'Herramienta mesoamericana de molienda conservada en hogares y cocinas mexicanas.'),
  jarrito: review('cocina', 'Vasija de barro asociada con café, atole y bebidas servidas en México.'),
  teleteatro: review('medios', 'Formato televisivo recordado por generaciones que vieron nacer la televisión mexicana.'),
  sobremesa: review('familia', 'La entrada la sitúa en la conversación prolongada de la comida familiar dominical.'),
  apapacho: review('lenguaje', 'Voz afectiva especialmente reconocible en el español cotidiano de México.'),
  provecho: review('familia', 'Cortesía dicha al acercarse a una mesa, práctica cotidiana entre familias mexicanas.'),
  mande: review('lenguaje', 'Respuesta cortés muy característica de la crianza y convivencia en México.'),
  aguas: review('lenguaje', 'Advertencia coloquial inmediatamente reconocible en conversaciones mexicanas.'),
  ahorita: review('lenguaje', 'Expresión mexicana cuyo alcance temporal se entiende mediante el contexto.'),
  pilón: review('mercado', 'Cantidad de cortesía ligada a la relación entre marchantes y clientela en México.'),
  chiquihuite: review('artesanía', 'Canasta de fibras y nombre de origen náhuatl presente en hogares mexicanos.'),
  petate: review('artesanía', 'Estera de palma de raíz mesoamericana usada en la vida cotidiana mexicana.'),
  radionovela: review('medios', 'Recuerdo sonoro que reunió a familias mexicanas alrededor del radio.'),
  atole: review('cocina', 'Bebida de maíz de larga continuidad y numerosas variantes regionales mexicanas.'),
  champurrado: review('cocina', 'Bebida de masa y chocolate ligada al desayuno y los tamales en México.'),
  'pan dulce': review('cocina', 'Conchas y cuernitos evocan la visita cotidiana a panaderías mexicanas.'),
  cajeta: review('cocina', 'Dulce de leche de cabra con tradición especialmente reconocida en México.'),
  'historieta mexicana': review('medios', 'Objeto de lectura popular situado explícitamente en la tradición editorial nacional.'),
  tiendita: review('barrio', 'Comercio pequeño esencial en la vida cotidiana de colonias y pueblos mexicanos.'),
  vecindad: review('barrio', 'Forma de vivienda colectiva emblemática de la memoria urbana de Ciudad de México.'),
  sonidero: review('barrio', 'Cultura de baile y saludos con arraigo particular en barrios de Ciudad de México.'),
  cascarita: review('barrio', 'Partido improvisado con mochilas como porterías, escena común de barrios mexicanos.'),
  talacha: review('lenguaje', 'Voz coloquial mexicana para el trabajo manual de reparación y mantenimiento.'),
  cuate: review('lenguaje', 'Voz coloquial mexicana para una amistad o compañía cercana.'),
  'Cine de Oro': review('medios', 'Periodo histórico central para la memoria cinematográfica popular de México.'),
};

module.exports = { MEXICO_VIVIDO_WORDS, REMOVED_WORDS, FIRST_FIFTY_CONTEXT_REVIEW, SEMANTIC_CONCEPT_OVERRIDES };
